d/rules: add i386 and x32 to list of low-mem arches
starting with 1.60, they are no longer able to build rustdoc because the
rustc_driver.so file is too large (>1G) and cannot be mmap-ed:

[...]
error[E0786]: found invalid metadata files for crate `rustc_driver`
  --> src/librustdoc/lib.rs:43:1
   |
43 | extern crate rustc_driver;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: failed to mmap file '/<<PKGBUILDDIR>>/build/x86_64-unknown-linux-gnux32/stage1/lib/rustlib/x86_64-unknown-linux-gnux32/lib/librustc_driver-55ecdc7db120b4be.so': Cannot allocate memory (os error 12)

Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>